### ISSUE TITLE
Feedback not useable as Triggers. Add Connection Variables.

### ISSUE THREAD

**Issue by joelengelhardt** [bitfocus/companion-module-malighting-msc#3]
Please make the current Feeback options (Executor active state, Executor paused state, Cue list, Fader position) all proper Companion Variables. This will enable Triggering events and banks from this data in dot2.

Thank you for the work you all have already done on this project, and for looking into this issue!

**Comment by tap-chris** [comment]
Fader position is already available as Variable but you have to add the Executor to the `Receiver Executor List` in the settings. Active/Paused state and active cue could be added. I'll add this as soon as possible.

Thanks and enjoy :)

**Comment by cameronaffleck** [comment]
Would be good to get the active cue feedback displayed on buttons via variables, if possible! Tried to fork it myself and have a look but my laptop isn't compiling Companion correctly....
Love using this module for work, and the active cue as a variable would be the icing on the cake!

**Comment by tap-chris** [comment]
I've added those variables for you guys. Sorry for the delay.
Will push this after testing and might have to add an update script.

**Comment by cameronaffleck** [comment]
> I've added those variables for you guys. Sorry for the delay.
> 
> Will push this after testing and might have to add an update script.

Cheers Christian - much appreciated

**Comment by joelengelhardt** [comment]
> I've added those variables for you guys. Sorry for the delay. Will push this after testing and might have to add an update script.

Thank you, Christian! Thanks for your generous work on this project!

**Comment by jryan324** [comment]
Hi Chris!

Was the active cue number added as a Variable? I cant see it anywhere in the instance!

**Comment by istnv** [comment]
Feedback triggers and additional variables included in the update for Companion v3.0

**Comment by joelengelhardt** [comment]
> Feedback triggers and additional variables included in the update for Companion v3.0

Hi there, I just installed 3.0.0-rc1+5909-v3-0.0-rc1-725c3583. In this version, an error shows that the dot2 module has not been updated for v3.0. This way, no variables are available at all from this module--not even the previously available Fader Position variable.

**Comment by joelengelhardt** [comment]
> Feedback triggers and additional variables included in the update for Companion v3.0

Hi there, I just installed 3.0.0-rc1+5909-v3-0.0-rc1-725c3583. In this version, an error shows that the dot2 module has not been updated for v3.0. This way, no variables are available at all from this module--not even the previously available Fader Position var

**Comment by joelengelhardt** [comment]
> Feedback triggers and additional variables included in the update for Companion v3.0

Hi there, I just installed 3.0.0-rc1+5909-v3-0.0-rc1-725c3583. In this version, an error shows that the dot2 module has not been updated for v3.0. This way, no variables are available at all from this module--not even the previously available Fader Position variable.

Additionally, no dot2 Feedbacks are available in the Trigger page conditions sections. Instead, it just reads, "No feedbacks match the search."

Please reopen this issue.

**Comment by istnv** [comment]
It will not work until the updated module gets included. It should already be in the v3.0 releases. 
I'll submit again.  The variables had to be modified, read the docs.
